{"name": "Ошибка входа с неверным паролем", "status": "passed", "steps": [{"name": "Попытка вход под несуществующим пользователем", "status": "passed", "start": 1749813749241, "stop": 1749813749659}], "start": 1749813749240, "stop": 1749813749659, "uuid": "ce97c769-4f79-409e-82ad-aa762e45643b", "historyId": "94b475b8696fd8c415c17ece03df27c2", "testCaseId": "94b475b8696fd8c415c17ece03df27c2", "fullName": "tests.test_login_user.TestLoginUser#test_auth_with_wrong_password", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login_user"}, {"name": "subSuite", "value": "TestLoginUser"}, {"name": "host", "value": "DESKTOP-5MH90VS"}, {"name": "thread", "value": "13380-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_user"}]}